### ISSUE TITLE
reliable update speed

### ISSUE THREAD

**Issue by iamthe1st** [xs5871/esphome-tsic#1]
Hi,
i am thinking about building a "Temperature" Controller for my old Espresso machine.
(When Temperature is lower then target-Temperature switch GPIO to high -> This switches a Solid-State-Relay to high and activates the heater; Switch off when temperature is hotter then target + 1°C).
ESPhome would be neat for OTA Updates -  my Source codes never work at first try :-)

I am interested in using the TSIC as a temperature-Sensor.

How fast can you read the TSIC Temperature reliably?

I would like to read it 1 or 2 times a second - can i do this with this library?

**Comment by xs5871** [comment]
The sensor update interval is decoupled from the ESPHome update cycle. The former is set at the factory (usually 100ms) and can not be adjusted; the sensor spits out readings periodically and doesn't care if anything is reading those values. This component handles every one of those updates in an interrupt and buffers them until ESPHome asks for an update, so 100ms is the limit at which you can read new values. (You can update faster, but you'll read the same value more than once).

Since you mentioned espresso machines -- you may be interested in one of my other projects: [esphome-coffee](https://github.com/xs5871/esphome-coffee)

**Comment by iamthe1st** [comment]
Thank you for your helpful reply and sharing your source code!

I replaced the Water-Pump on my 10 year old Saeco Arome Espresso machine yesterday evening - no it works again like "new".
But what i discovered: The pump pumps the water faster then the weak heating unit can heat it up, although i manually cleaned it completely.
So even when i hit the "Steam button" the temperature drops while pumping and the Status indicator switches to "need heating". So a "PID" controller can not help much here, because the heater is too weak.

So as long as my Seaco Aroma is alive, i will keep it like it is. 
But my next machine will be added with temperature controller - and maybe your source code :-)

**Comment by xs5871** [comment]
That is a functionality I tacked onto the PID controller that comes with ESPHome.
If the current temperature is below the steady state regime or a brewing process is detected via temperature gradient, the PID control is by-passed and the heater runs at 100%.
Anyway, I'm don't want to try to convince you to use my project, just an FYI.

I'll close this issue as resolved.
